### ISSUE TITLE
LNBits Melt issue / method not allowed

### ISSUE THREAD

**Issue by me639276639936** [cashubtc/cashu#252] opened 2023-06-13 00:02 UTC
When I try to pay a 29,000 sat invoice even though I have a non-pending balance of 30,000 sats I get this error.

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://legend.lnbits.com/cashu/api/v1/************/melt

If I go to the URL in browser it shows as : {"detail":"Method Not Allowed"}

**Comment by AngusP** [comment] 2023-06-16 10:58
`{"detail":"Method Not Allowed"}` because `/melt` is a POST API ([source code](https://github.com/cashubtc/cashu/blob/67caf5f53254a04db453953cc059004d41b726d1/cashu/mint/router.py#L153-L158))

The earlier 400 is probably because something didn't work out correctly or the request wasn't quite right. Need more info to be able to see what that could be

**Comment by callebtc** [comment] 2023-06-23 14:00
Hi there, sorry for the late reply, I was gone for a while. Can you tell us how to reproduce this bug?

**Comment by me639276639936** [comment] 2023-06-23 18:24
I already cut my losses, deleted the mint in question and stopped working on it. It was basically locking funds as pending. It seemed like it would allow to send unsettled funds but would not allow it to come out of pending status. 

Cashu.me I think was the issue. When I switched to Nutstash it had an option to break that pending status… I sound like an idiot.

**Comment by callebtc** [comment] 2023-06-28 10:33
Alright! The token is marked as pending in the wallet db but that should not affect whether you can actually use it or not. The mint also has a pending state, but that should not differ from wallet to wallet. Closing!

**Closed by callebtc** 2023-06-28 10:33 UTC
Labels: help wanted, mint
